title: dataking820's Research Blog
description: Study Blog for Artificial Intelligence

url: https://dataking820.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 10

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: brianmaierjr
  twitter: brianmaierjr
  facebook: brianmaierjr
  email: gustmd820@gmail.com
  linkedin: brianmaierjr

#google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr
